/* ----------------------------------------------
 * Generated by Animista on 2022-8-15 16:23:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

import { keyframes } from "styled-components";

/**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
 export const slideLeft = keyframes`
 0% {
    -webkit-transform: translateX(-400px);
            transform: translateX(-400px);
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
 `;

 export const pulse = keyframes`
0% {
        fill: #19dcea;
      }
      100% {
        fill: #b22cff;
      }
 `;
